### ISSUE TITLE
[Feature] Добавить возможности включать стили в проект без @font-face правил

### ISSUE THREAD

**Issue by dkshichkovskiy** [zyfra/Prizm#1047]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [x] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [x] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`

### Предложение

В пакетах `@prizm-ui/components`, `@prizm-ui/icons`, `@prizm-ui/theme` имеются стили, которые необходимы для корректного отображения компонентов Prizm. Так же в этих стилях есть конструкции `@font-face`, регистрирующие нужные шрифты. 

Например:

```css
@font-face {
  font-family: 'Inter var';
  font-weight: 100 900;
  font-style: normal;
  font-named-instance: 'Regular';
  src: url('Inter-upright.var.woff2') format('woff2');
}
```

Т.к. в урле до шрифта естественно нет ни какого baseHref для текущего приложения, браузер пытается грузить данный шрифт относительно хоста. В итоге получаем 404 ошибку. 

Необходима возможность включать в проект стили без регистрации самих шрифтов через `@font-face`. Чтобы регистрация шрифтов происходила в самом приложении, динамически подставляя нужный baseHref.
