### ISSUE TITLE
[Feature] Tabs нужна css переменная для указания максимальной ширины

### ISSUE THREAD

**Issue by bree7e** [zyfra/Prizm#1244]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

_Tabs_ 
https://prizm.site/components/tabs

### Предложение

_Работаю в рамках задачи проекта СОУ_ "Учёт движения - таб вкладки обрезается не доходя до максимальной ширины"
Нужно увеличить максимальную ширину до 400px.

Предлагаю сделать css переменную для max-width таба. Сейчас прибито 200px. Предлагаю добавить переменную с fallback. Например такую:

```css
.tabs > prizm-tabs prizm-tab button {
    max-width: var(--prizm-tabs__tab-button-max-width, 200px);
}
```

**Comment by bree7e** [comment]
Извиняюсь: изначально неверно сформулировал постановку. 200px это был вот такой костыль в проекте. 
```css
    ::ng-deep {
      prizm-tab {
        button {
          max-width: 200px;
        }
      }
   }
```
В призме хотелось бы добавить возможность ограничивать максимальную ширину таба, чтобы имя таба обрезалось в три точки. Вот такой финт:

![image](https://github.com/zyfra/Prizm/assets/26089012/0a2b0278-c08a-4425-84f1-a3201a06d6cc)

Тогда можно будет обходится без костыля в проекте.
