### ISSUE TITLE
[Feature] @prizm-ui/components - `[prizmButton]` with icon and without text should appear like `[prizmIconButton]`

### ISSUE THREAD

**Issue by AleksandrSibiakov** [zyfra/Prizm#2361]
### Библиотека

- [ ] `@prizm-ui/core`
- [x] `@prizm-ui/components`
- [ ] `@prizm-ui/install`
- [ ] `@prizm-ui/icons`
- [ ] `@prizm-ui/icons-loader`
- [ ] `@prizm-ui/flag-icons`
- [ ] `@prizm-ui/theme`
- [ ] `@prizm-ui/charts`
- [ ] `@prizm-ui/ast`
- [ ] `@prizm-ui/nx-plugin`
-

### Компонент

_PrizmButtonComponent_

### Предложение

При попытке шаблонизации кнопок (например для тулбаров) возникает сложность объединения кнопок и иконочных кнопок. Из за этого шаблон разрастается до "некрасивого"
`@if (model.icon) ... [prizmIconButton] ... @else ... [prizmButton] `, т.к. дефолтные стили завязаны на наличие аттрибута, хотя директива (класс) одна и все биндинги остальные дублируются.
Без этой правки выглядит так [иконка без текста](https://prizm.site/components/button/Live_demo?tuiMode=null&icon=agenda-fill&ng-content=&size=xl&appearanceType=outline): 

![Image](https://github.com/user-attachments/assets/2c3f3cfa-d085-4e60-bbdc-d0164af93f83)

Предлагаю включить стили, чтобы, по большому счету, отпала необходимость использования `prizmIconButton` 

```css
// Allows to use [prizmButton] directive instead of [prizmIconButton]
[prizmButton]:has(prizm-icons-full ~ .text:empty) {
  aspect-ratio: 1 / 1;

  > prizm-wrapper {
    padding: 0;
    display: flex;
    align-items: center;
    justify-content: center;
  }
}
```

В этом случае если у кнопки указана ТОЛЬКО иконка, она будет выглядеть как `prizmIconButton` (стили те же, за исключением `aspect-ratio`, которая позволяет избежать хардкода ширины иконочной кнопки (т.к. высота уже прописана для размерной сетки)
